services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    #volumes:
    #  - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 20s
    env_file: ".env"

  api:
    build: backend/.
    pull_policy: build
    depends_on:
      db:
        condition: service_healthy
    env_file: ".env"
    ports:
      - "8000:8000"

  frontend:
    profiles: [frontend]
    build: frontend/.
    pull_policy: build
    volumes:
      - ./legal:/usr/share/nginx/html/legal
    depends_on:
      - api
    env_file: ".env"
    ports:
      - "3000:80"

#volumes:
#  postgres_data:
