<script lang="ts">
	import Sparkles from 'lucide-svelte/icons/sparkles';
</script>

<span
	class="ml-1 inline-flex items-center gap-1 rounded bg-muted px-1.5 py-0.5 text-xs text-muted-foreground"
	title="This comment was auto-generated by Xcode"
>
	<Sparkles class="size-3 shrink-0" />
	auto-generated
</span>
